### ISSUE TITLE
Missing mintlify in the document package dependencies

### ISSUE THREAD

**Issue by matheusho** [haydenbleasel/next-forge#169]
Run dev is interrupted because `mintily command not found`

![image](https://github.com/user-attachments/assets/305e3eb3-45db-4097-8787-4764f00b0b2b)

**Comment by haydenbleasel** [comment]
Sorry about that, Mintlify is actually a global CLI install. I've updated the Setup page to reflect that, but in the meantime check out https://mintlify.com/docs/development
