### ISSUE TITLE
Unclear install instructions. Misleading env var handling

### ISSUE THREAD

**Issue by jackblackCH** [haydenbleasel/next-forge#173]
1. Essential environment variables are not clearly documented for project initialization
2. Location for configuring the DATABASE_URL is not specified, even after creating a Postgres database on Neon and evenetually adapting in the correct .env file. 
3. After setting DATABASE_URL correctly, Studio error still says that it fails to locate public.Pages", seeding scripts needed?

**Comment by jackblackCH** [comment]
I'm glad to hear that. I came from Guillermo's post and I think you'll receive way more traffic from happy testers as a result. 

I would highly recommend ensuring that a fresh project created from scratch, following the installation page instructions, runs without issues. Clear instructions are important to make the first attempt successful.

**Comment by haydenbleasel** [comment]
Absolutely. I’ll work through that this week. If you have any more specific feedback, drop it here and I’ll make sure it gets covered.

**Comment by jackblackCH** [comment]
Hey! You might want to test your own setup flow a few more times from scratch. I've tried it twice now and kept running into the same stuff 😅

Main issues:
- Right after setup, the CLI tells you to start the project but that just leads to errors because you need like a million ENV vars set up (Google Analytics and whatnot). Maybe make most of these optional or add some defaults?

- The DATABASE_URL seems essential and is still especially tricky. Can't get Prisma Studio working and when I try setting the URL manually, I get these errors:
  - "Error in Prisma Client request"
  - "The table `public.Page` doesn't exist in the database"

Would be super helpful to have better docs that walk through everything needed for a fresh install with an empty env file. Just my 2 cents from a new user perspective! 👍
