### ISSUE TITLE
Missing mintlify dependency

### ISSUE THREAD

**Issue by needcaffeine** [haydenbleasel/next-forge#177]
The first `pnpm run dev` fails if you don't have mintlify already installed globally.

**Comment by haydenbleasel** [comment]
This is noted in the setup, it's meant to be installed globally: https://www.next-forge.com/docs/setup#mintlify-cli

**Comment by willwillis** [comment]
ehhhh... but those of us with rolling-release OS'es can't install globally without potentially breaking future updates/upgrades. Is there no other way to accomplish this without touching the global npm install?

**Comment by crummy** [comment]
It's weird to me that the `npx` command at the top and bottom of the home page doesn't install all the required dependencies. Maybe it could output "please make sure mintlify is installed globally" at the bottom of its output or something like that?
