### ISSUE TITLE
Duplicate env var files post setup.

### ISSUE THREAD

**Issue by michxymi** [haydenbleasel/next-forge#178]
I'm not sure if that's intentional or not, but post the `npx next-forge init [my-project]` we end up with both a `env.local` and `.env.example` files in all the apps. From a quick glance they look identical so my suggestion (got a PR coming) is to update the bash script to `mv` those files to `.env.local` rather than creating a copy.

**Comment by haydenbleasel** [comment]
Correct and on purpose - I tend to keep the `.env.example` files for reference. When someone else clones your project, they need to know what the env var file should look like as they're not committed to the repo (at least, I really hope you don't 😂)

**Comment by michxymi** [comment]
I see, that makes sense.
