### ISSUE TITLE
Invalid Environment Variables error

### ISSUE THREAD

**Issue by V473r10** [haydenbleasel/next-forge#180]
Hello!

I've been trying to run this project but I'm getting an Invalid env vars error

![image](https://github.com/user-attachments/assets/6aa5460d-d7b1-4d42-9d4d-a6ce8609d8dc)

I've filled every required env var

![image](https://github.com/user-attachments/assets/aa30ccc0-fbb2-458f-a3a6-d78f301462ee)

I don't know if I missing something. I would really appreciate if anyone can help me.

**Comment by mashafrancis** [comment]
Experiencing the same here.

**Comment by haydenbleasel** [comment]
Hey @V473r10, sorry to hear you're having trouble! Can you confirm that this .env.local file exists in all 3 required directories?

- /apps/app
- /apps/web
- /apps/api

**Comment by V473r10** [comment]
Hi Hayden!

I can confirm you that the .env.local file exists in all 3 required dirs. 

I'm the same guy in X with the same trouble that share you the browser and server logs via Warp Blocks.

I'm noticing also in the call stack are mentioned something about ../../packages/design-system/providers/posthog.tsx and the ../../packages/design-system/lib/analytics/client.ts

Perhaps I'm setting something wrong at Posthog host? I'm not sure which value I have to set there.

Thanks for your kindly help buddy!

**Comment by V473r10** [comment]
Just trying, if I hardcode the variables in ../../packages/design-system/providers/posthog.tsx and  ../../packages/design-system/lib/analytics/client.ts then the error changes to apps/web/app/components/header/index.tsx and if I hardcode them there too the app just loads

**Comment by TharinduX** [comment]
Experiencing the same issue here. I couldnt get local server to work. Getting Invalid env vars error.

**Comment by hcusto** [comment]
I'm encountering the same issue. I've added the environment variables to all three env files, and they log correctly on the server side, so the setup seems correct. However, they aren't accessible on the client side. When I set them as optional in the schema, PostHog returns an error saying the token is not set.

To log them, you can use the code below. Just add it to packages/env/index.ts

`function validateEnvVariables(
  schema: Partial<Record<string, z.ZodType>>,
  prefix: 'client' | 'server'
) {
  const missing: string[] = [];
  const invalid: string[] = [];

  Object.entries(schema).forEach(([key, validator]) => {
    if (!validator) return; // Skip if validator is undefined
    const value = process.env[key];
    console.log("ENVVAR#" + key, value);
    
    if (value === undefined && !validator.isOptional()) {
      missing.push(key);
      return;
    }

    const result = validator.safeParse(value);
    if (!result.success && value !== undefined) {
      invalid.push(`${key}: ${result.error.message}`);
    }
  });

  if (missing.length > 0 || invalid.length > 0) {
    console.error(`\n❌ Invalid environment variables:\n`);
    
    if (missing.length > 0) {
      console.error(`Missing ${prefix} variables:`);
      missing.forEach(key => console.error(`  - ${key}`));
    }
    
    if (invalid.length > 0) {
      console.error(`\nInvalid ${prefix} variables:`);
      invalid.forEach(error => console.error(`  - ${error}`));
    }
    
    console.error('\nPlease check your .env files and ensure all required variables are set correctly.\n');
  }
}


validateEnvVariables(server, 'server');
validateEnvVariables(client, 'client');
`

**Comment by haydenbleasel** [comment]
Hey folks. Doing a fresh `init` to debug this now. Will get you an update ASAP.

**Comment by haydenbleasel** [comment]
Okay, followed the process and am indeed getting `Invalid environment variables` but only on `web` which is interesting. On `app` I get some Prisma nonsense:

```
../../node_modules/.pnpm/@prisma+client@5.21.1_prisma@5.21.1/node_modules/@prisma/client/default.js:2:1
Module not found: Can't resolve '.prisma/client/default'
  1 | module.exports = {
> 2 |   ...require('.prisma/client/default'),
    | ^
  3 | }
  4 |

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
../../packages/database/index.ts
./app/(authenticated)/page.tsx
```

**Comment by haydenbleasel** [comment]
Okay I've fixed the analytics-related problem. It still seems as though none of the client variables are being passed to the web project. I'll keep digging.

**Comment by haydenbleasel** [comment]
Found the issue - I tried to cheat and dynamically load env vars. Doesn't work like that. Should be fixed now.
