### ISSUE TITLE
pnpm migrate doesn't work

### ISSUE THREAD

**Issue by oalexdoda** [haydenbleasel/next-forge#183]
Hi!

Trying to run this command: `pnpm migrate` and it won't run because of a missing env var

https://www.next-forge.com/docs/orm

![Screenshot 2024-11-05 at 11 36 43 AM](https://github.com/user-attachments/assets/871e2a13-b84e-48d2-9174-cb9176c1f58f)

Might be related to https://github.com/haydenbleasel/next-forge/issues/180 - even though all env vars are added according to the .env.local examples.

**Comment by haydenbleasel** [comment]
That's right @Morpheusse, thanks for the heads up! I'm updating the docs now.
