### ISSUE TITLE
`FLAGS_SECRET` should be part of the .env.example files

### ISSUE THREAD

**Issue by oalexdoda** [haydenbleasel/next-forge#185]
When starting a new project, you gotta dig through all the docs to end up on the Vercel Flags SDK docs & find that `FLAGS_SECRET` is a required variable. It should be part of the .env.example considering it's not optional & it breaks apps otherwise.

https://vercel.com/docs/workflow-collaboration/feature-flags/flags-pattern-nextjs#set-up-flags_secret

**Comment by haydenbleasel** [comment]
Great catch @oalexdoda, thanks!
