### ISSUE TITLE
Missing root project task for `analyze`

### ISSUE THREAD

**Issue by oalexdoda** [haydenbleasel/next-forge#186]
The docs say you can run `analyze` in the project root, however it only works if you run it in each app's root. I believe it's missing a turbo task.

https://www.next-forge.com/docs/bundle-analysis

![image](https://github.com/user-attachments/assets/2ce686df-045a-432e-8caa-23a2cc4ef638)

**Comment by haydenbleasel** [comment]
Great catch @oalexdoda, thanks!
