### ISSUE TITLE
Error to deploy app and web on vercel

### ISSUE THREAD

**Issue by ktfth** [haydenbleasel/next-forge#191]
This error occurred to me when deploying, following the instructions of the documentation.

This log maybe relevant:

app:build: Type error: Cannot find module 'next-themes/dist/types' or its corresponding type declarations.

Have some kind of action to do here?

**Comment by haydenbleasel** [comment]
Hey, I believe I fixed this in a recent commit: https://github.com/haydenbleasel/next-forge/commit/8c9dde0c1f5a16cc55cf74a576fe0e5163c83631

Can you re-init and verify?

**Comment by ktfth** [comment]
Doing that, and I let you know.

**Comment by ktfth** [comment]
api:build: > Build error occurred
api:build: Error: Invalid environment variables
api:build:     at onValidationError (/vercel/path0/node_modules/.pnpm/@t3-oss+env-core@0.11.1_typescript@5.6.3_zod@3.23.8/node_modules/@t3-oss/env-core/dist/index.js:109:15)
api:build:     at createEnv (/vercel/path0/node_modules/.pnpm/@t3-oss+env-core@0.11.1_typescript@5.6.3_zod@3.23.8/node_modules/@t3-oss/env-core/dist/index.js:116:16)
api:build:     at createEnv (/vercel/path0/node_modules/.pnpm/@t3-oss+env-nextjs@0.11.1_typescript@5.6.3_zod@3.23.8/node_modules/@t3-oss/env-nextjs/dist/index.js:74:35)
api:build:     at Object.<anonymous> (/vercel/path0/packages/env/index.ts:57:36)
api:build:     at mod._compile (/vercel/path0/node_modules/.pnpm/next@15.0.2_@babel+core@7.26.0_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/build/next-config-ts/require-hook.js:67:33)
api:build:     at require.extensions.<computed> (/vercel/path0/node_modules/.pnpm/next@15.0.2_@babel+core@7.26.0_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/build/next-config-ts/require-hook.js:69:20)
api:build:  ELIFECYCLE  Command failed with exit code 1.
api:build: ERROR: command finished with error: command (/vercel/path0/apps/api) /pnpm9/node_modules/.bin/pnpm run build exited (1)
api#build: command (/vercel/path0/apps/api) /pnpm9/node_modules/.bin/pnpm run build exited (1)
  Tasks:    1 successful, 2 total
  

---

  This error are happening to me, but all env var are filled
