### ISSUE TITLE
Error on env vars

### ISSUE THREAD

**Issue by ktfth** [haydenbleasel/next-forge#194]
api:build: > Build error occurred
api:build: Error: Invalid environment variables
api:build: at onValidationError (/vercel/path0/node_modules/.pnpm/https://github.com/t3-oss+env-core@0.11.1_typescript@5.6.3_zod@3.23.8/node_modules/@t3-oss/env-core/dist/index.js:109:15)
api:build: at createEnv (/vercel/path0/node_modules/.pnpm/https://github.com/t3-oss+env-core@0.11.1_typescript@5.6.3_zod@3.23.8/node_modules/@t3-oss/env-core/dist/index.js:116:16)
api:build: at createEnv (/vercel/path0/node_modules/.pnpm/https://github.com/t3-oss+env-nextjs@0.11.1_typescript@5.6.3_zod@3.23.8/node_modules/@t3-oss/env-nextjs/dist/index.js:74:35)
api:build: at Object. (/vercel/path0/packages/env/index.ts:57:36)
api:build: at mod.compile (/vercel/path0/node_modules/.pnpm/next@15.0.2https://github.com/babel+core@[7.26.0_@opentelemetry](mailto:7.26.0_@opentelemetry)+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/build/next-config-ts/require-hook.js:67:33)
api:build: at require.extensions. (/vercel/path0/node_modules/.pnpm/next@[15.0.2_@babel](mailto:15.0.2_@babel)+core@[7.26.0_@opentelemetry](mailto:7.26.0_@opentelemetry)+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/build/next-config-ts/require-hook.js:69:20)
api:build:  ELIFECYCLE  Command failed with exit code 1.
api:build: ERROR: command finished with error: command (/vercel/path0/apps/api) /pnpm9/node_modules/.bin/pnpm run build exited (1)
api#build: command (/vercel/path0/apps/api) /pnpm9/node_modules/.bin/pnpm run build exited (1)
Tasks: 1 successful, 2 total

This error are happening to me, but all env var are filled, have some change I need to do on my side?

**Comment by haydenbleasel** [comment]
Hi @ktfth, which version of next-forge are you using? Check the `package.json` version field - I may have recently fixed this

**Comment by haydenbleasel** [comment]
@gt-codes can you tell me which version of next-forge you are using? Check the `package.json` version field.

**Comment by yamz8** [comment]
I had similar issue , added latest to the init command 
https://github.com/haydenbleasel/next-forge/compare/main...yamz8:next-forge:patch-1

**Comment by brianreworded** [comment]
I am having the same issue as well -- using version `2.12.8`
