### ISSUE TITLE
Failed to fetch configuration

### ISSUE THREAD

**Issue by ktfth** [haydenbleasel/next-forge#195]
app:build:    Linting and checking validity of types ...
app:build:    Collecting page data ...
app:build: Error: Failed to collect configuration for /
app:build:     at <unknown> (/vercel/path0/node_modules/.pnpm/next@15.0.2_@babel+core@7.26.0_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/build/utils.js:1130:23)
app:build:     at async Span.traceAsyncFn (/vercel/path0/node_modules/.pnpm/next@15.0.2_@babel+core@7.26.0_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/trace/trace.js:153:20) {
app:build:   [cause]: Error: @prisma/client did not initialize yet. Please run "prisma generate" and try to import it again.
app:build:       at new o (/vercel/path0/apps/app/.next/server/app/(authenticated)/page.js:26:17304)
app:build:       at 82150 (/vercel/path0/apps/app/.next/server/app/(authenticated)/page.js:22:444)
app:build:       at Function.t (/vercel/path0/apps/app/.next/server/webpack-runtime.js:1:485)
app:build:       at async getLayoutOrPageModule (/vercel/path0/node_modules/.pnpm/next@15.0.2_@babel+core@7.26.0_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/app-dir-module.js:37:15)
app:build:       at async collectAppPageSegments (/vercel/path0/node_modules/.pnpm/next@15.0.2_@babel+core@7.26.0_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/build/segment-config/app/app-segments.js:50:45)
app:build:       at async (/vercel/path0/node_modules/.pnpm/next@15.0.2_@babel+core@7.26.0_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/build/utils.js:1128:28)
app:build:       at async Span.traceAsyncFn (/vercel/path0/node_modules/.pnpm/next@15.0.2_@babel+core@7.26.0_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/trace/trace.js:153:20)

After load as global some env vars, the app failed with this error, do you have any clues?

**Comment by haydenbleasel** [comment]
Hi @ktfth, I think it may be this line:

```
app:build: [cause]: Error: @prisma/client did not initialize yet. Please run "prisma generate" and try to import it again.
```

Is your database and local Prisma schema in sync?

**Comment by ktfth** [comment]
I'm gonna test again, but using neon service.

**Comment by TharinduX** [comment]
You need to run the migration before starting the server. Can we add this to the docs under setup?

**Comment by haydenbleasel** [comment]
Ah great point, I added it as a build script but not during setup. If you can submit a PR to add it to setup.sh I’ll merge it. Otherwise I’ll handle it when I’m back at my laptop.

**Comment by ktfth** [comment]
By the way, I'm using windows, so dropping the windows script here as a PR: https://github.com/haydenbleasel/next-forge/pull/196

**Comment by ktfth** [comment]
After run the migration, everything goes well. Thank you!

**Comment by haydenbleasel** [comment]
Awesome I'll review that other PR and close this one out. Thanks for verifying!

**Comment by ktfth** [comment]
After run the migration everything goes well.
