### ISSUE TITLE
12.2 - Error with create-flag.ts

### ISSUE THREAD

**Issue by jcchrrr** [haydenbleasel/next-forge#201]
Hello @haydenbleasel,
Good job, you're doing fast and well 💪 

I'm encountering an issue : 
-> I launch `pnpm dev --filter=web`
-> The server console log : 

``` 
⨯ app/(home)/page.tsx (24:8) @ betaFeature
web:dev:  ⨯ ReferenceError: betaFeature is not defined
web:dev:     at Home (./app/(home)/page.tsx:34:13)
web:dev:     at AsyncLocalStorage.run (node:async_hooks:346:14)
web:dev:     at stringify (<anonymous>)
web:dev:     at AsyncLocalStorage.run (node:async_hooks:346:14)
web:dev:     at AsyncResource.runInAsyncScope (node:async_hooks:206:9)
web:dev: digest: "572898164"
web:dev:   22 |   return (
web:dev:   23 |     <>
web:dev: > 24 |       {betaFeature && (
web:dev:      |        ^
web:dev:   25 |         <div className="w-full bg-black py-2 text-center text-white">
web:dev:   26 |           Beta feature now available
web:dev:   27 |         </div>
```

-> and the browser console : 
![image](https://github.com/user-attachments/assets/d3efc749-b03d-48ab-9832-9b745abb789a)

I dont really know if is coming from clerk, analytics or feature-flags,
don't really understand this part.

Have you an idea ?

**Comment by haydenbleasel** [comment]
Hi @jcchrrr, sorry about this - it was `log.ts` trying to access `process.env.NODE_ENV`.
