### ISSUE TITLE
Add a suggestion to the docs to symlink env vars?

### ISSUE THREAD

**Issue by paulgrieselhuber** [haydenbleasel/next-forge#207]
I'm not sure if this is a good idea or not, so not creating a PR for the docs yet (happy to if you like).

To avoid maintaining multiple copies of the `.env.local` file in development, I just symlinked from a copy in the root of the project to `apps/app/.env.local`, `apps/api/.env.local`, `apps/web/.env.local` and `packages/database/.env`.

Much better from a workflow standpoint. Any reason not to do this?

**Comment by haydenbleasel** [comment]
@paulgrieselhuber I didn't even think about that 😮 If it works, that would be phenomenal! I'd love to see a PR if you have the time!
