### ISSUE TITLE
Feature Request: Support for Custom Authentication Methods

### ISSUE THREAD

**Issue by rajanshresth** [haydenbleasel/next-forge#223]
The project is currently configured to use Clerk for authentication. However, some developers, including myself, have specific use cases that require custom authentication methods, which would be easier to implement with Auth.js. Adding support for custom authentication would allow greater flexibility and enable integration with various authentication providers not supported by Clerk.
**Use Case:**
In our scenario, we need to implement a custom authentication mechanism that involves unique user data validations and security checks. While Clerk is great, it doesn’t fully support our requirements, and Auth.js would allow us to define custom authentication logic directly.

**Comment by DaniEnsi** [comment]
Yes, I agree it would be really cool to see some of the new auth providers like [Better Auth](https://www.better-auth.com/) integrated too...

**Comment by haydenbleasel** [comment]
Currently working with @Bekacru on a Better Auth guide! Stay tuned.

**Comment by DaniEnsi** [comment]
Thats great to hear! Really cool project 🔥

**Comment by DaniEnsi** [comment]
@haydenbleasel Is there any timeline for when this is going to be done?

**Comment by DaniEnsi** [comment]
@haydenbleasel Do you have any idea when this is going to be done?

**Comment by haydenbleasel** [comment]
@DaniEnsi we have an auth.js migration guide here:  https://docs.next-forge.com/authentication/authjs 

More guides coming soon for other providers.

**Comment by Bekacru** [comment]
> @haydenbleasel Do you have any idea when this is going to be done?

I'm working on it. I just wanted to wait until we have v1, hopefully this week!

**Comment by DaniEnsi** [comment]
> > @haydenbleasel Do you have any idea when this is going to be done?
> 
> 
> 
> I'm working on it. I just wanted to wait until we have v1, hopefully this week!

That great to hear! Really loving what you are doing with better-auth. Have never seen such a large feature set in self hosted auth providers, like the passkeys and integrated org. support! 🙌

**Comment by haydenbleasel** [comment]
@DaniEnsi BetterAuth guide is now live! https://docs.next-forge.com/authentication/better-auth

**Comment by guptaashwanee** [comment]
BetterAuth has very limited providers

**Comment by Bekacru** [comment]
> BetterAuth has very limited providers

Feel free to open an issue to request a specific provider on our [repo](https://github.com/better-auth/better-auth). Also, you can use the [Generic OAuth Plugin](https://www.better-auth.com/docs/plugins/generic-oauth) to easily add any provider yourself.
