### ISSUE TITLE
Feature Request: Support for lemon squeezy payment option

### ISSUE THREAD

**Issue by Milind-Jamnekar** [haydenbleasel/next-forge#227]
I like the template a lot. It would be awesome to have a lemon squeezy payment integration option. I would love to use stripe but it's  not supported In my country (india). If possible I would try to do the code for it as well.

**Comment by haydenbleasel** [comment]
Sounds good! I'll ping the Lemon Squeezy team on X to see if they're keen to collab on a guide.

**Comment by haydenbleasel** [comment]
Done! Let me know if you get stuck or need any further documentation.

https://docs.next-forge.com/migrations/payments/lemon-squeezy
