### ISSUE TITLE
Feature Request: Enhance repo/env with Granular Service-Based Environment Variable Validation

### ISSUE THREAD

**Issue by enolcasielles** [haydenbleasel/next-forge#228]
Currently, the `repo/env` package enforces validation of all required environment variables for the different services involved (Clerk, Stripe, Resend, etc.), which means that **all applications or packages using** `repo/env` **must define all environment variables**, regardless of whether they need them or not. I have seen [an issue](https://github.com/haydenbleasel/next-forge/issues/207) suggesting the creation of a symlink to a file at the project root, which I believe is a very good solution to improve the development experience. However, this approach would still leave some issues unresolved.

## Proposed Solution

I propose a more granular solution that allows grouping environment variables by service. The idea is to use **boolean flag variables** to enable or disable specific services at the application level. By default, services would be disabled. Each app would first set the flag variable of the required service to true and then define the necessary variables for that service. The `repo/env` package would evaluate which services are active and would configure the validation schema accordingly.

This approach would:

1. Allow each application to activate only the services it requires through the corresponding flags.
2. Ensure each application only defines the environment variables relevant to the active services.

## Next Steps

If this proposal is of interest, I am willing to create a PR with the necessary changes to implement it.

**Comment by haydenbleasel** [comment]
Hey @enolcasielles cool idea! Definitely open to checking out a PR that implements this.

**Comment by DrHazemAli** [comment]
Feature added on PR #252

**Comment by enolcasielles** [comment]
I’d suggest something [like this](https://github.com/haydenbleasel/next-forge/compare/main...enolcasielles:next-forge:issue-228-granular-env). This approach remains compatible with previous versions. If the ENABLE_SERVICES_FLAGS environment variable is not defined, everything works as it did before. Alternatively, we could modify this behavior and make flag variables mandatory. I’d like to hear your thoughts on which approach is better, @haydenbleasel.

In any case, when this behavior is enabled, the functionality is straightforward: all variables are divided into services. The user must specify which services a single app needs to use. Once a service is enabled, all related variables are checked.

The commit also includes a sample env.example file.

**Comment by haydenbleasel** [comment]
Working on it here: https://github.com/haydenbleasel/next-forge/pull/332
