### ISSUE TITLE
Possibility to select package manager (bun, pnpm, npm, yarn :| ) while creating a project.

### ISSUE THREAD

**Issue by fstodulski** [haydenbleasel/next-forge#232]
**Is your feature request related to a problem? Please describe.**
When creating a project, I’m unable to choose my preferred package manager (bun, pnpm, npm, or yarn), which adds extra steps to set it up manually.

**Describe the solution you’d like**
A prompt during project setup to select the package manager, automatically configuring the project with the chosen option.

**Describe alternatives you’ve considered**
Switching package managers manually after setup, which requires deleting files and reinstalling dependencies.

**Comment by HyperDanisH** [comment]
I'd like to work on this issue. Please assign it to me.

**Comment by fstodulski** [comment]
For sure, it's no only about that, but also "workspaces:" are defined differently for some of them.

**Comment by HyperDanisH** [comment]
> For sure, it's no only about that, but also "workspaces:" are defined differently for some of them.

I will try to find a way out.

**Comment by haydenbleasel** [comment]
Resolved in https://github.com/haydenbleasel/next-forge/commit/aa4bf9929b47be303b78900afe7a4140683fa11b!

When you initialize the project, just pass `--package-manager bun` or whatever you prefer!

https://docs.next-forge.com/setup/installation#initialization
