### ISSUE TITLE
Error on running init script on Windows

### ISSUE THREAD

**Issue by TheCukitoDev** [haydenbleasel/next-forge#234]
**Describe the bug**
The instlling script doesen't work propperly on Windows

**next-forge version**
I am using version 2.13.21

**To Reproduce**
1. Get a Windows machine
2. Run `pnpm dlx next-forge@latest init test`

**Expected behavior**
It should do the same thing as on Linux. I tested it in both platforms and in Linux there is no error

**Screenshots**
![image](https://github.com/user-attachments/assets/d0aa976e-646b-4b32-9f6e-342305cbdd38)

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro V 10.0.22631 compation 22631
 - Browser Brave v 1.73.89

**Comment by haydenbleasel** [comment]
Hi @TheCukitoDev, I've rewritten the setup scripts so they're platform-agnostic via Node.js.

I then tested on a Windows machine, appeared to work just fine sans the specific architecture Turborepo can run on.

I documented my findings here: https://docs.next-forge.com/setup#operating-system

Let me know if you run into any other issues!

**Comment by TheCukitoDev** [comment]
Yes it seems working now!! Thanks
