### ISSUE TITLE
Main app doesn't run on Endeavour OS

### ISSUE THREAD

**Issue by syndg** [haydenbleasel/next-forge#238]
**Describe the bug**
The main app starts but does not load the main page

**next-forge version**
I am using version 2.14.1
This is the latest right now but this happened in the previous versions as well.

**To Reproduce**
1. Run `pnpm dev --filter app`

**Expected behavior**
The "/" page should load.

**Solutions Tried**
1. Tried removing `.next/` and `node_modules` and reinstalling, did not work

**Screenshots**
![image](https://github.com/user-attachments/assets/194bca8b-8bb8-4440-8600-57e429e98aec)

**Desktop (please complete the following information):**
 - OS: Endeavour OS (Linux)
 - Browser: Google Chrome

**Comment by haydenbleasel** [comment]
@syndg Thanks for filing this! Can you confirm for me you've filled out all the required environment variables?

**Comment by syndg** [comment]
Hey @haydenbleasel  yes, I have filled out all of the required environment variables.

**Comment by haydenbleasel** [comment]
Okay, I'll spin up a repl.it and try to repro 👍

**Comment by haydenbleasel** [comment]
Okay, I wasn't able to repro but here were the steps I took:

1. `npx next-forge@latest init test`, let the installer run
2. Open `apps/app/.env.local`, fill out every variable
3. Run `pnpm dev --filter app`
4. Open localhost:3000

Appears to run fine with no errors in the Terminal.

I'm running MacOS Sequoia so perhaps it's an OS-related thing.

I'll try to repro on a Endeavour OS environment.

**Comment by syndg** [comment]
Thanks @haydenbleasel  yeah, it's really weird, I followed the setup guide from the docs step by step a lot of times but it's giving me the same issue. Even tried switching to an older version of `nodejs`, it's probably OS side as you mentioned.

**Comment by haydenbleasel** [comment]
Gotcha. I'm not sure I have the chops to figure out the underlying OS issue, however I will go and verify that next-forge works on certain OS' rather than expecting it to, and update the docs accordingly.

**Comment by haydenbleasel** [comment]
@syndg I've documented my findings here: https://docs.next-forge.com/setup#operating-system.

If you manage to find a way to get Endeavour OS working, let me know!

**Comment by gauravmandall** [comment]
Is there any way to use it on Arch linux ??
