### ISSUE TITLE
Nextauth setup guide in docs

### ISSUE THREAD

**Issue by nicholsss** [haydenbleasel/next-forge#239]
Hi! I’d like to suggest adding a guide to the documentation on setting up NextAuth (authjs.dev) as an additional authentication option.

**Comment by haydenbleasel** [comment]
I'd love that! @balazsorban44 keen to collab with me on this? I think I shot you a message on Discord recently.

**Comment by innovatorved** [comment]
This project is fantastic! It would be greatly appreciated if you could provide a migration guide for transitioning from Clerk to NextAuth.

**Comment by haydenbleasel** [comment]
Working on it now ^
