### ISSUE TITLE
Make environment variables optional

### ISSUE THREAD

**Issue by haydenbleasel** [haydenbleasel/next-forge#251]
The reliance on 30ish environment variables makes next-forge difficult to spin up quickly. I originally decided to implement it this strictly to avoid production errors when missing env vars.

I'm thinking it might be better to make them optional and have the existence of the key affect whether the feature is "enabled" or not. Open to thoughts and suggestions on this one.

Related issues:

- https://github.com/haydenbleasel/next-forge/issues/247
- https://github.com/haydenbleasel/next-forge/issues/228

Server:

- [ ] CLERK_SECRET_KEY
- [x] CLERK_WEBHOOK_SECRET
- [ ] RESEND_FROM
- [ ] DATABASE_URL
- [ ] RESEND_TOKEN
- [ ] STRIPE_SECRET_KEY
- [x] STRIPE_WEBHOOK_SECRET - https://github.com/haydenbleasel/next-forge/commit/6aa3314060c8987268e7ac01506a02ba13a11fef
- [x] BETTERSTACK_API_KEY - https://github.com/haydenbleasel/next-forge/commit/98d7d5ec138c15051818e1f504c55822e4682492
- [x] BETTERSTACK_URL - https://github.com/haydenbleasel/next-forge/commit/98d7d5ec138c15051818e1f504c55822e4682492
- [x] ARCJET_KEY - #327 
- [x] ANALYZE
- [x] SVIX_TOKEN - https://github.com/haydenbleasel/next-forge/commit/3fc4e144f866c502ab58dc584383cf0a0658aab9
- [x] LIVEBLOCKS_SECRET
- [x] OPENAI_API_KEY
- [x] SENTRY_ORG
- [x] SENTRY_PROJECT
- [x] VERCEL
- [x] NEXT_RUNTIME
- [x] FLAGS_SECRET - https://github.com/haydenbleasel/next-forge/commit/86e88f181fc4a9f9ab53b659550d82c87b757754

Client:
- [ ] NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
- [x] NEXT_PUBLIC_CLERK_SIGN_IN_URL (can't remove, but added default)
- [x] NEXT_PUBLIC_CLERK_SIGN_UP_URL (can't remove, but added default)
- [x] NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL (can't remove, but added default)
- [X] NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL (can't remove, but added default)
- [ ] NEXT_PUBLIC_APP_URL
- [ ] NEXT_PUBLIC_WEB_URL
- [x] NEXT_PUBLIC_API_URL
- [x] NEXT_PUBLIC_DOCS_URL - https://github.com/haydenbleasel/next-forge/commit/64d2e4cebb2232e821ad223dc56dc07faa0d37ca
- [x] NEXT_PUBLIC_GA_MEASUREMENT_ID - https://github.com/haydenbleasel/next-forge/commit/a2a7b5f95ffdf6aff45e5cce558769c5e5a77c36
- [ ] NEXT_PUBLIC_POSTHOG_KEY
- [ ] NEXT_PUBLIC_POSTHOG_HOST
- [ ] NEXT_PUBLIC_VERCEL_PROJECT_PRODUCTION_URL

**Comment by davidmytton** [comment]
I'd suggest splitting into two categories: core and optional (or enhanced, advanced, or something different). 

For example, auth and Prisma/database are both core - you can't build a SaaS product without them. But analytics and payments aren't needed to bootstrap a new project - you would enable them later.

**Comment by oldbettie** [comment]
Agreed. Another good solution would be to have the env variables for non core packages stored in the package themselves and have the packages themselves feature toggled. This would be more work though

**Comment by nandorojo** [comment]
Huge upvote on this one. I want to test out the project before creating a ton of SaaS accounts, but I can't deploy it or find a demo URL.

**Comment by oldbettie** [comment]
> Huge upvote on this one. I want to test out the project before creating a ton of SaaS accounts, but I can't deploy it or find a demo URL.

some of them you can just set fake values to get the project running locally. Maybe I will put up a pr that sets this in the .env.example file. You might get some errors in the terminal but I was able to get it running with just a few real env variables

**Comment by haydenbleasel** [comment]
I've made the first steps towards this with our new Collaboration feature:

https://github.com/haydenbleasel/next-forge/blob/33b28ad9d8ffe5b072b4e092cbd0be88200582f8/apps/app/app/(authenticated)/page.tsx#L62

**Comment by wowjulian** [comment]
What do you think of just using feature flags to make things optional?

For example, you can have `analytics` feature flag and call analytics related functions (that requires certain env variables) only when it's enabled.

**Comment by matthewmuscat** [comment]
Same goes for `FLAGS_SECRET` and `SVIX_TOKEN`? No mention of these anywhere, does anyone know where these are set?

**Comment by haydenbleasel** [comment]
@matthewmuscat The `SVIX_TOKEN` is provided when you register for a [Svix](https://www.svix.com/) account.

As for `FLAGS_SECRET`, there's a section on [this page](https://docs.next-forge.com/env#app-environment-variables) that shows you how to generate one.

**Comment by pedrocarlo** [comment]
Hey, maybe you could create a preset or base environment file, and let users extend with their own file. It would also make it easier to have variables defined for each app. 

Here is the docs for how to do it with t3-env: https://env.t3.gg/docs/customization 

What do you think?

**Comment by mikerkeating** [comment]
i've started using the project this week and have got setup. It's great so far.

I'm +1 on the idea of making services optional. I spent quite a lot of non-productive time to setup the SAAS apps in order to get the env vars. 

I'd also like them to be optional on a per app-basis.

- I've copied the `web` folder and now have `web-home`, `web-blog`, `web-shop`. These would all be updated on separate schedules and have different integrations, so we have them as separate apps. 
- However, they are served on the same sub-domain with different paths (example.com; example.com/blog; example.com/shop)
- With they way that vercel hosts monorepos ([via a proxy with rewrites](https://vercel.com/docs/monorepos/monorepo-faq#how-can-i-make-my-projects-available-on-different-paths-under-the-same-domain) ), I'm currently blocked by a problem with clerk and redirects - frustratingly I don't need Clerk anyway on the web apps.  
- I can use separate subdomains for the actual SAAS app and API so would not see this problem there

**Comment by haydenbleasel** [comment]
Making more progress on this, but I like @pedrocarlo's idea of making env var requirements composable e.g. 

```ts
import cms from '@repo/cms/keys';

export const env = createEnv({
  // Require a `BASEHUB_TOKEN`
  extends: [cms()],
});
```
