### ISSUE TITLE
Does next-forge recommend using separate domains between web and app?

### ISSUE THREAD

**Issue by wowjulian** [haydenbleasel/next-forge#260]
What's the "default" approach to using custom domains?

Something like "app.mydomain.com", "web.mydomain.com", "api.mydomain.com"? 

From the doc, I'm reading that api, web, app are supposed to be separate projects in Vercel.

I'm assuming this likely means three different domains are expected. If this is correct, I think this could be useful to be documented.

**Comment by haydenbleasel** [comment]
https://docs.next-forge.com/structure/apps
