### ISSUE TITLE
Convert repository to a template

### ISSUE THREAD

**Issue by idkgene** [haydenbleasel/next-forge#261]
The repository is designed as a boilerplate and starting point for launching new SaaS app as quickly as possible, but it's not currently set up as an official GitHub template repository. This makes it **slightly** 🤏 less convenient for users to quickly start new projects based on this boilerplate.

I propose converting this repository into an official GitHub template repository. This would allow users to easily create new repositories with the same directory structure and files as this project with just a few clicks.

Docs for this: https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-template-repository#creating-a-template-repository

For excluding certain folders & files we can try JetBrains approach: https://github.com/JetBrains/intellij-platform-plugin-template/blob/deb171483598ee8a5d7621154db880e87b4db4ef/.github/workflows/template-cleanup.yml

**Comment by haydenbleasel** [comment]
@idkgene Done! Thanks for the great suggestion 👍 

![CleanShot 2024-11-17 at 10 50 46@2x](https://github.com/user-attachments/assets/7ce61682-72ff-43b2-b895-378da1ee65be)
