### ISSUE TITLE
Typescript Alias import error

### ISSUE THREAD

**Issue by blackstarxr253** [haydenbleasel/next-forge#267]
**Describe the bug**
When launching the "app" app after signing in, I am getting a Module not found error. 
It seems to be due to typescript trying to use the typescript-config package as the root for relative imports.

**next-forge version**
I am using version 2.16.4

**To Reproduce**
1. supply all env vars
2. run pnpm dev -or- npm run dev
3. access localhost:3000 and sign in via clerk

**Expected behavior**
the app should load correctly

**Screenshots**
![Screenshot 2024-11-19 at 9 43 24 AM](https://github.com/user-attachments/assets/f0bbdd96-f2d5-46d7-aa5d-8aca22b5ddb0)

**Possible Fix**
If I edit the apps/app/tsconfig.json file and add a paths override, the error goes away and the app functions correctly
```json
{
  "extends": "@repo/typescript-config/nextjs.json",
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "@/*": ["./*"]
    }
  },
  "include": [
    "next-env.d.ts",
    "next.config.ts",
    "**/*.ts",
    "**/*.tsx",
    ".next/types/**/*.ts"
  ]
}
```

**Desktop (please complete the following information):**
 - OS: MacOS Sequoia 15.2
 - Browser: Chrome v131

**Comment by haydenbleasel** [comment]
Thanks @blackstarxr253, seems it was working in VS Code but not in dev as the alias was being interpreted differently.
