### ISSUE TITLE
Web: Header is not responsive, overlapping elements and partial text on small mobile devices

### ISSUE THREAD

**Issue by pierDipi** [haydenbleasel/next-forge#280]
**Describe the bug**

![image](https://github.com/user-attachments/assets/22d6fc95-db80-4599-9f0c-16d9bfe44cba)

**next-forge version**

`latest`, `v2.16.15`

**To Reproduce**

1. `pnpm dev`
2. Go to `http://localhost:3001/`
3. Select a small screen device in dev tools (like IPhone SE)

**Expected behavior**

No overlapping elements nor partial text on small mobile devices

**Screenshots**

![image](https://github.com/user-attachments/assets/22d6fc95-db80-4599-9f0c-16d9bfe44cba)

**Desktop (please complete the following information):**
 - OS: any
 - Browser: any

**Comment by oalexdoda** [comment]
![image](https://github.com/user-attachments/assets/740007f0-9e3f-493f-bfd4-d10508c1ea7a)

desktop too
