### ISSUE TITLE
Broken layout on first boot

### ISSUE THREAD

**Issue by oalexdoda** [haydenbleasel/next-forge#284]
Even if you get past the org 404 bug in https://github.com/haydenbleasel/next-forge/issues/283 the app looks like this:

![image](https://github.com/user-attachments/assets/3d0b608a-9683-41f8-865d-1932adc6a4bd)

No sidebar, the button to "uncollapse" it doesn't work, etc. Is this due to some compiler issue where the styles aren't kicking in at all?

**Comment by oalexdoda** [comment]
Update: this was related to using bun instead of pnpm.

**Comment by firstaxel** [comment]
Please how we fix this cause I am having the same issues or it only occurs once
