### ISSUE TITLE
Add Next-Safe-Action as default for server actions

### ISSUE THREAD

**Issue by pedrocarlo** [haydenbleasel/next-forge#321]
**Is your feature request related to a problem? Please describe.**
Logging and analytics and auth in server actions can be repetitive with clerk and posthog

**Describe the solution you'd like**
Next Safe Action with middleware can solve this problem easily and provide optimisitcUpdates and much more. 

**Describe alternatives you've considered**
React Query

https://next-safe-action.dev/docs/define-actions/middleware

**Comment by haydenbleasel** [comment]
@pedrocarlo Cool idea! If you've got time, I'd love to see a PR so I can understand the impact 🙏

**Comment by pedrocarlo** [comment]
> @pedrocarlo Cool idea! If you've got time, I'd love to see a PR so I can understand the impact 🙏

On my list of things to do! Maybe in a day or two I will have a PR.
