### ISSUE TITLE
Bun as a package manager

### ISSUE THREAD

**Issue by guptaashwanee** [haydenbleasel/next-forge#322]
Is there any specific reason for not using bun instead of pnpm as a package manager? 

Because I see buns give a cleaner workspace and, it also doesn't create node modules inside apps and packages.

**Comment by hsavit1** [comment]
pnpm is standard for turborepo and i dont see the benefit of switching

**Comment by haydenbleasel** [comment]
Done! Feel free to start a new project with:

```
npx next-forge init@latest my-app --package-manager bun
```

**Comment by guptaashwanee** [comment]
I would like to know, how to setup text based lock file using bun, is it required while starting a project or when bun install?
