### ISSUE TITLE
Bug: Update script fails to upgrade from 2.20.3 to 2.20.11

### ISSUE THREAD

**Issue by Ad-amS** [haydenbleasel/next-forge#333]
**Describe the bug**
The `npx next-forge@latest update` command fails to update the project from version 2.20.3 to 2.20.11. The script runs but doesn't make any changes to the codebase.

**next-forge version**
I am using version 2.20.3 trying to update to 2.20.11

**To Reproduce**
1. Have a next-forge project at version 2.20.3
2. Run `npx next-forge@latest update --from 2.20.3 --to 2.20.11`
3. Script completes but no changes are made to codebase
4. Package.json version remains at 2.20.3

**Expected behavior**
The update script should:
- Update the codebase with any changes from 2.20.3 to 2.20.11
- Update package.json version to 2.20.11
- Apply any template changes that occurred between versions

**Screenshots**
![bug](https://github.com/user-attachments/assets/a6151681-f751-47ab-8fc3-4244aef28013)

**Desktop (please complete the following information):**
 - OS: MacOS Sequoia 15.1.1
 - Node: v22.12.0

**Comment by haydenbleasel** [comment]
Hey @Ad-amS thanks for letting me know! Did the files appear anywhere else e.g. maybe outside the repo, in the parent folder?

**Comment by haydenbleasel** [comment]
nvm - found the issue. Side effect of testing a script locally 😂  Fixing now.

**Comment by haydenbleasel** [comment]
@Ad-amS Should be fixed now! Tested in prod:

![CleanShot 2024-12-09 at 17 08 29@2x](https://github.com/user-attachments/assets/c3d186fe-3b04-4121-bbff-e4c4e590515d)

![CleanShot 2024-12-09 at 17 08 33@2x](https://github.com/user-attachments/assets/ee6c56e9-2f80-4c06-a29f-28ec31c1e521)

**Comment by Ad-amS** [comment]
works great now, thanks a lot for such a quick fix, much appreciated!
