### ISSUE TITLE
Why ignore design system in biome config?

### ISSUE THREAD

**Issue by zommerberg** [haydenbleasel/next-forge#337]
I noticed that the design system is explicitly excluded from biome.json

```
{
  "extends": ["ultracite"],
  "files": {
    "ignore": [
      "packages/design-system/components/ui/**",
      "packages/design-system/lib/**",
      "packages/design-system/hooks/**",
      "apps/docs/**/*.json"
    ]
  }
}
```

Is there a reason for doing so? Does it have something to do with the monorepo limitations of biome?

**Comment by haydenbleasel** [comment]
Added some more documentation around it here: https://docs.next-forge.com/faq#why-are-certain-folders-ignored-by-the-linting-configuration
