### ISSUE TITLE
the code with default initialization will find many warnings & errors with lint（npx ultracite)

### ISSUE THREAD

**Issue by desenmeng** [haydenbleasel/next-forge#338]
**Describe the bug**
the code with default initialization will find many warnings & errors with lint（npx ultracite)

**next-forge version**
I am using version 2.20.17

**To Reproduce**
npx ultracite

**Expected behavior**
no error

**Screenshots**
![image](https://github.com/user-attachments/assets/227543c0-7b87-4455-93b5-41c9cfb89048)

![image](https://github.com/user-attachments/assets/5f07f7cb-1004-49ff-a848-2bf852310a12)

**Desktop**
 - OS: MacOS

**Comment by haydenbleasel** [comment]
Thanks @desenmeng, I'm currently tweaking Ultracite so it's less demanding when it comes to these types of checks :+1:
