### ISSUE TITLE
created two env file in database packages when init new project

### ISSUE THREAD

**Issue by yamz8** [haydenbleasel/next-forge#339]
**Describe the bug**
the init command create botch .env and .env.local in the database package

**next-forge version**
2.20.18

**Screenshots**
![image](https://github.com/user-attachments/assets/f0ffe496-c373-4742-8254-e4fc2ea3d215)

**Comment by haydenbleasel** [comment]
Found the issue and fixed it! Thanks for the heads up 🙏
