### ISSUE TITLE
Where is the header of this page?

### ISSUE THREAD

**Issue by asionesjia** [haydenbleasel/next-forge#351]
![image](https://github.com/user-attachments/assets/e941a61e-3263-4fa5-a5b2-3e7b17b070f3)

**Where is the header of this page?**
https://www.next-forge.com/

**Comment by asionesjia** [comment]
I want to achieve the effect of hsah smooth scrolling. I want to find an example.

**Comment by haydenbleasel** [comment]
Hi @asionesjia, you can find the header here! https://github.com/haydenbleasel/next-forge/blob/main/splash/app/components/header/index.tsx

However, the real trick to smooth scrolling is this `scroll-smooth` class in the layout file: https://github.com/haydenbleasel/next-forge/blob/main/splash/app/layout.tsx#L30

Hope this helps!
