### ISSUE TITLE
Where is /api/chat? Getting a 404

### ISSUE THREAD

**Issue by PierrickLozach** [haydenbleasel/next-forge#359]
Hey,

trying to follow your chat recipe however I get a 404 for http://localhost:3000/api/chat.

I can't seem to find what code is running when calling /api/chat? as there is no `chat` folder in my `api` folder?
Or maybe I am missing some files?

Thanks!

**Comment by haydenbleasel** [comment]
Hi @PierrickLozach, did you create the chat route listed in [step 4](https://docs.next-forge.com/recipes/ai-chatbot#4-create-the-chatbot-api-route)? The code that calls API chat is listed in step 3 i.e.

```ts
useChat({
  onError: handleError,
  api: '/api/chat',
});
```

**Comment by haydenbleasel** [comment]
I did just notice a minor typo in the chat route name ^

**Comment by PierrickLozach** [comment]
That was it, thanks!
