### ISSUE TITLE
@repo to @company

### ISSUE THREAD

**Issue by guptaashwanee** [haydenbleasel/next-forge#365]
**Is your feature request related to a problem? Please describe.**
It is actually not a problem but just a question, is there any way to change @repo to @company in the projects.

**Comment by haydenbleasel** [comment]
Hey @guptaashwanee absolutely! Just do a find-and-replace of `@repo` to `@company`, then run `pnpm install`.

**Comment by guptaashwanee** [comment]
Ohh, it is that simple, I thought while installing there will be any option to do that. Thanks man
