### ISSUE TITLE
Does not seem to build on MacOS

### ISSUE THREAD

**Issue by timmeade** [haydenbleasel/next-forge#50]
I am working on a M1 Mac.

This does not seem to work on it.  

Contentlayer on pnpm dev (or yarn dev) stops at:

```
Contentlayer config change detected. Updating type definitions and data...
```

On research i found that 'yarn build' needs to be run in the vscode terminal. As it will not run in macos terminal.  I verified this is true.   Upon running under vscode I get:

```
> Build error occurred
Error: Failed to collect page data for /_not-found
    at /Users/tim/Code/labs/next-forge-working/node_modules/.pnpm/next@14.1.0_@babel+core@7.23.0_@opentelemetry+api@1.6.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/utils.js:1258:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  type: 'Error'
}
error Command failed with exit code 1.
```

Pulling the plug on this now.  Looks great on paper but not enough time currently to fix these issues.  Maybe later.

Tim

**Comment by timmeade** [comment]
Looks like contentlayer is not being maintained currently:

https://github.com/contentlayerdev/contentlayer/issues/615

Seems to be issue I am seeing

**Comment by timmeade** [comment]
OK I took a shot and run pnpm dev inside vscode terminal.

I was able to get the first page.  

Note:  the prisma studio is still throwing and error.

**Comment by haydenbleasel** [comment]
Yeah I'm running into that contentlayer problem intermittently. Might swap out for next/mdx.

@timmeade What error is Prisma Studio throwing?

**Comment by haydenbleasel** [comment]
Hey folks, might be fixed now that the deps are bumped and I migrated to the temp contentlayer2 fork. Let me know how you go.
